### ISSUE TITLE
Problems understanding the rfft

### ISSUE THREAD

**Issue by certainlyWrong** [GommeAntiLegit/SonopyJava#1]
I'm debugging your code with a small buffer and I noticed that infinite loops happen.

Please can you help me understand a little more about how to use your rfft and how it works. This was the buffer I used:

float[] buffer = {1, 2, 3, 4, 5, 6, 7, 8, 9, 5, 3, 2, 6, 10};
float[][] result = rfft(buffer, buffer.length);

**Comment by mikex86** [comment]
Well, as you can see in FFT.java, I'm not the original author of this function.
I merely adapted it to behave similar to np.fft.rfft to achieve model compatibility between the Java Inference code and the Python training code.
The original authors are credited to be Danny Su and Hanns Holger Rutz.

It seems though as if the algorithm was made with the assumption that numPoints is a power of two and that numPoints <= signal.length.
Note that the size of signal.length is not the problem here, because even a buffer length of 2 works, as long as numPoints is a power of 2 smaller or equal to the signal length.
While you can get the algorithm to work outside of these conditions in some cases, it is very clear that those are the intended input constraints.

**Comment by certainlyWrong** [comment]
Now everything became clearer. Thank's for your time!
